### ISSUE TITLE
Row is re-mounting on resize.

### ISSUE THREAD

**Issue by colemars** [mckervinc/react-fluid-table#19] opened 2020-08-04 16:10 UTC
Even with the width set to `100%`.

Looking at previous versions it looks like this hasn't always been the case.

**Comment by mckervinc** [comment] 2020-09-02 14:44
Ok thanks for the heads up! I'll take a look

**Comment by mckervinc** [comment] 2020-09-06 17:28
@colemars if I understand your comment correctly, this may be expected behavior. if you resize the width of the window when the row height is not explicitly set, it is possible that a lot less rows will be in the DOM. See [here](https://mckervinc.github.io/react-fluid-table/#/variable). If you make the window too small, a row that may have been mounted could disappear. For example, say this was the table before resizing:

<img width="1318" alt="Screen Shot 2020-09-06 at 1 26 03 PM" src="https://user-images.githubusercontent.com/5893816/92331445-abdc3800-f044-11ea-9674-41972f9b3792.png">

and this is the table after shrinking the window horizontally:

<img width="680" alt="Screen Shot 2020-09-06 at 1 26 48 PM" src="https://user-images.githubusercontent.com/5893816/92331449-b991bd80-f044-11ea-883e-a5baae0135a1.png">

The row with ID = 5 would dismount because it's no longer in the visible window/part of the overscan. if you were to expand the window again, that row would re-mount.

**Comment by colemars** [comment] 2020-09-06 18:07
@mckervinc Here's a quick reproduction 

https://codesandbox.io/s/tender-mahavira-nuhxm?file=/src/Example.js

Try selecting the checkbox on the top row and then resize the screen.

**Comment by mckervinc** [comment] 2020-09-07 22:39
@colemars this should be fixed in version 0.4.2. See the code changes here: https://github.com/mckervinc/react-fluid-table/commit/c4acbe49b71a3bc329b5ae987164de349e3f25ba

**Closed as completed** 2020-09-08 20:48 UTC
Labels: bug
